function paramsOut = MasterGUI(hObject, callbackdata, userData, EEG) %#ok<INUSL>
geometry = {1, [1, 1], [1, 1], [1, 1]};
geomvert = [1,1,1,1];
title = 'PREP pipeline control panel';
inputData = struct('signal', EEG, 'name', title, 'userData', userData);
closeOpenWindows(inputData.name);
uilist= {{'style', 'text', 'string', 'Override default parameters for processing step:'}...
    {'style', 'pushbutton', 'string', 'Boundary', ...
    'Callback', {@boundaryGUI, inputData}} ...
     {'style', 'pushbutton', 'string', 'Reference', ...
    'Callback', {@referenceGUI, inputData}} ...
    {'style', 'pushbutton', 'string', 'Detrend', ...
    'Callback', {@detrendGUI, inputData}} ...
     {'style', 'pushbutton', 'string', 'Report', ...
    'Callback', {@reportGUI, inputData}} ...
    {'style', 'pushbutton', 'string', 'Line noise', ...
    'Callback', {@lineNoiseGUI, inputData}}...
    {'style', 'pushbutton', 'string', 'Post process', ...
    'Callback', {@postProcessGUI, inputData}}};
[~, paramsOut] = inputgui('geometry', geometry, 'geomvert', geomvert, ...
    'uilist', uilist, 'title', title, ...
    'helpcom', 'pophelp(''pop_prepPipeline'')');

end % MasterGUI