function [paramsOut] = reportGUI(hObject, callbackdata, inputData) %#ok<INUSL>
title = 'Report parameters';
reportModeRadioValues = {'Normal', 'Skip', 'Report Only'};
reportModeValues = {'normal', 'skipReport', 'reportOnly'};
b = '';
defaultStruct = inputData.userData.report;
reportModeCallback = ['R = findobj(gcf, ''Tag'', ''reportMode''); ' ...
    'set(R, ''value'', 0); h = gcbo; set(h, ''value'', 1); s = get(h,''string''); ' ...
    'clear h s R;'];
reportCallback   = ['defaultFile = get(findobj(''parent'', gcbf, ''tag'', ''reportName''), ''String'');' ...
    ' [tmpfile tmppath] = uiputfile(''.pdf'', ''Enter filename'', defaultFile); drawnow;' ...
    'if tmpfile ~= 0,' ...
    '    set(findobj(''parent'', gcbf, ''tag'', ''reportName''), ''string'', fullfile(tmppath, tmpfile));' ...
    'end;' ...
    'clear tmpuserdat tmpfile tmppath;'];
summaryCallback   = [' defaultFile = get(findobj(''parent'', gcbf, ''tag'', ''summaryName''), ''String'');' ...
    ' [tmpfile tmppath] = uiputfile(''.html'', ''Enter filename'', defaultFile); drawnow;' ...
    'if tmpfile ~= 0,' ...
    '    set(findobj(''parent'', gcbf, ''tag'', ''summaryName''), ''string'', fullfile(tmppath, tmpfile));' ...
    'end;' ...
    'clear tmpuserdat tmpfile tmppath;'];
while(true)
    mainFigure = findobj('Type', 'Figure', '-and', 'Name', inputData.name);
    userdata = get(mainFigure, 'UserData');
    if isempty(userdata) || ~isfield(userdata, 'report')
        paramsOut = struct();
    else
        paramsOut = userdata.report;
    end
    [defaultStruct, errors] = checkStructureDefaults(paramsOut, defaultStruct);
    
    if ~isempty(errors)
        warning('reportGUI:bad parameters', getMessageString(errors)); %#ok<CTPCT>
    end
    reportModeRadioValue = defaultStruct.reportMode.value;
    if defaultStruct.publishOn.value
        publishCheckValue = 1;
    else
        publishCheckValue = 0;
    end
    %creates a structure for the text color of each parameter and sets them
    %all to black
    fNamesDefault = fieldnames(defaultStruct);
    for k = 1:length(fNamesDefault)
        textColorStruct.(fNamesDefault{k}) = 'k';
    end
    report = [defaultStruct.reportFolder.value ...
        defaultStruct.reportName.value];
    summary = [defaultStruct.summaryFolder.value ...
        defaultStruct.summaryName.value];
    geometry = {[1,1,1,1], [1, 1],  [1,2,1], [1,2,1]};
    geomvert = [];
    closeOpenWindows(title);
    uilist = {{'style', 'text', 'string', 'Report mode:', ...
        'TooltipString', defaultStruct.reportMode.description}...
        {'style', 'radiobutton',  ...
        'String', 'Normal', ...
        'Value', isReportModeDefault(reportModeRadioValue, 'normal'), ...
        'tag', 'reportMode', ...
        'callback', reportModeCallback, ...
        'ForegroundColor', textColorStruct.reportMode} ...
        {'style', 'radiobutton',  ...
        'String', 'Skip', ...
        'Value', isReportModeDefault(reportModeRadioValue, 'skipReport'), ...
        'tag', 'reportMode', ...
        'callback', reportModeCallback, ...
        'ForegroundColor', textColorStruct.reportMode} ...
        {'style', 'radiobutton',  ...
        'String', 'Report only', ...
        'Value', isReportModeDefault(reportModeRadioValue, 'reportOnly'), ...
        'tag', 'reportMode', ...
        'callback', reportModeCallback, ...
        'ForegroundColor', textColorStruct.reportMode} ...
        {'style', 'text', 'string', 'Publish on', ...
        'TooltipString', defaultStruct.publishOn.description}...
        {'style', 'checkbox', 'Value', publishCheckValue, ...
        'tag', 'publishOn', 'ForegroundColor', textColorStruct.publishOn}...
        {'style', 'text', 'string', 'Report file name'}...
        {'style', 'edit', 'string', report, 'tag', 'reportName', 'userdata', 'reportName'}...
        {'style', 'pushbutton', 'string', 'Browse', 'callback', reportCallback, 'userdata', 'reportName'}...
        {'style', 'text', 'string', 'Summary file name'}...
        {'style', 'edit', 'string', summary, 'tag', 'summaryName'}...
        {'style', 'pushbutton', 'string', 'Browse', 'callback', summaryCallback, 'userdata', 'summaryName'}};
    [outparam, userdat, ~, paramsOut] = inputgui('geometry', geometry, ...
        'geomvert', geomvert, 'uilist', uilist, 'title', title, ...
        'helpcom', 'pophelp(''pop_prepPipeline'')');
    if isempty(paramsOut)
        break;
    end
    defaultFile = get(findobj('parent', mainFigure, 'tag', 'reportMode'), 'Value');
    [pathstr,name,ext] = fileparts(paramsOut.summaryName);
    paramsOut.summaryName = [name ext];
    paramsOut.summaryFolder = [pathstr filesep];
    [~,name,ext] = fileparts(paramsOut.reportName);
    paramsOut.reportName = [name ext];
    paramsOut.reportFolder = [pathstr filesep];
    
    [paramsOut, typeErrors, fNamesErrors] = ...
        changeType(paramsOut, defaultStruct);
    
    mainFigure = findobj('Type', 'Figure', '-and', 'Name', inputData.name);
    userdata = get(mainFigure, 'UserData');
    userdata.report = paramsOut;
    set(mainFigure, 'UserData', userdata);
    if isempty(typeErrors)
        break;
    end
    textColorStruct = highlightErrors(fNamesErrors, ...
        fNamesDefault, textColorStruct);
    displayErrors(typeErrors); % Displays the errors and restarts GUI
end

    function isDefault = isReportModeDefault(default, value)
        isDefault = strcmpi(default, value);
    end

    function reportMode = getReportModeFromStr(str)
        index = strcmpi(str, reportModeRadioValues);
        reportMode = reportModeValues{index};
    end

end