function report = generateIssueReport(collectionStats, datasetIndex)
% Generates an issue report for datasetIndex from collection
if nargin < 2
    error('generateIssueReport:NotEnoughArgs', ...
        'generateIssueReport requires collection statistics and index args');
elseif datasetIndex < 1 || ...
        datasetIndex > size(collectionStats.statistics, 1)
    error('generateIssueReport:DataIndexOutOfBounds', ...
        ['datasetIndex should be in [1, ' ...
        num2str(size(collectionStats.statistics, 1)) ']']);
end
report = '';

%% Report channels that couldn't be handled by the referencing
badChans = collectionStats.noisyChannels(datasetIndex);
if ~isempty(badChans.channelsStillBad)
    report = [report ...
        sprintf('Noisy channels not interpolated after referencing: %s\n', ...
        getListString(badChans.channelsStillBad))];
end
if 0.25*badChans.numberReferenceChannels < ...
        length(badChans.badChannelNumbers)
     report = [report sprintf('Data set has %d of %d channels bad\n', ...
               length(badChans.badChannelNumbers), ...
                      badChans.numberReferenceChannels)];                      
end   

%% Report unusual statistics
stats = collectionStats.statistics(datasetIndex, :);
s = collectionStats.statisticsIndex;

%% Median 
if stats(s.aveCorRef) > 0.91 && stats(s.medCorRef) > 0.95
    report = [report ... 
        sprintf('Max win correlation [median=%g, mean=%g]\n', ...
                stats(s.medCorRef), stats(s.aveCorRef))];
end

if stats(s.aveCorRef) > stats(s.medCorRef) > 0.9 || ...
   stats(s.aveCorRef) < stats(s.medCorRef) < 0.95 
   report = [report  ...
        sprintf('Referencing did not improve max win correlation [ref=%g, orig=%g]\n', ...
                stats(s.medCorRef), stats(s.medCorOrig))];
end
if stats(s.medDevRef) > stats(s.medDevOrig) 
   report = [report  ...
        sprintf('Referencing did not improve amplitude [ref=%g, orig=%g]\n', ...
                stats(s.medDevRef), stats(s.medDevOrig))];
end
if stats(s.medDevRef) > stats(s.medDevOrig) 
   report = [report  ...
        sprintf('Referencing did not improve overall amplitude [ref=%g, orig=%g]\n', ...
                stats(s.medDevRef), stats(s.medDevOrig))];
end
if stats(s.medWinDevRef) > stats(s.medWinDevOrig) 
   report = [report  ...
        sprintf('Referencing did not improve window amplitude [ref=%g, orig=%g]\n', ...
                stats(s.medWinDevRef), stats(s.medWinDevRef))];
end

