function reportRereference(noisyParameters, numbersPerRow, indent)
%% Extracts and outputs parameters for referencing calculation
    if ~isfield(noisyParameters, 'reference')
        fprintf('Signal wasn''t referenced\n');
        return;
    end
    reference = noisyParameters.reference;
    fprintf('%sRereferencing version %s\n', indent, ...
        noisyParameters.version.Reference);
    fprintf('%sSampling rate: %g Hz\n', indent, reference.noisyOut.srate);


    fprintf('%sNoisy channel detection parameters:\n', indent);
    fprintf('%s%sRobust deviation threshold (z score): %g\n', ...
        indent, indent, reference.noisyOut.robustDeviationThreshold);
    fprintf('%s%sHigh frequency noise threshold (ratio): %g\n', ...
        indent, indent, reference.noisyOut.highFrequencyNoiseThreshold);
    fprintf('%s%sCorrelation window size (in seconds): %g\n', ...
        indent, indent, reference.noisyOut.correlationWindowSeconds);
    fprintf('%s%sCorrelation threshold (with any channel): %g\n', ...
        indent, indent, reference.noisyOut.correlationThreshold);
    fprintf('%s%sBad correlation threshold: %g\n', ...
        indent, indent, reference.noisyOut.badTimeThreshold);
    fprintf('%s%s%s(fraction of time with low correlation)\n', ...
        indent, indent, indent);
    fprintf('%s%sRansac sample size : %g\n', ...
        indent, indent, reference.noisyOut.ransacSampleSize);
    fprintf('%s%s%s(number channels to use for interpolated estimate)\n', ...
        indent, indent, indent);
    fprintf('%s%sRansac channel fraction (for ransac sample size): %g\n', ...
        indent, indent, reference.noisyOut.ransacChannelFraction);
    fprintf('%s%sRansacCorrelationThreshold: %g\n', ...
        indent, indent, reference.noisyOut.ransacCorrelationThreshold);
    fprintf('%s%sRansacUnbrokenTime (input parameter): %g\n', ...
        indent, indent, reference.noisyOut.ransacUnbrokenTime);
    fprintf('%s%sRansacWindowSeconds (in seconds): %g\n', ...
        indent, indent, reference.noisyOut.ransacWindowSeconds);
    fprintf('%s%sRansacPerformed: %g\n', indent, indent, ...
        reference.noisyOut.ransacPerformed);
    fprintf('\n%sReference channels:\n', indent);
    printList(reference.referenceChannels, ...
        numbersPerRow, [indent, indent]);
    fprintf('\n%sRereferencedChannels:\n', indent);
    printList(reference.rereferencedChannels,  ...
        numbersPerRow, [indent, indent]);

    fprintf('\n\n%sNoisy channels before referencing:\n', indent);
    printList(reference.noisyOutOriginal.noisyChannels,  ...
        numbersPerRow, [indent, indent]);
    fprintf('\n%sNoisy channels interpolated after referencing:\n', indent);
    printList(reference.interpolatedChannels, numbersPerRow, [indent, indent]);
    fprintf('\n%sRemaining noisy channels:\n', indent);
    printList(reference.noisyOut.noisyChannels, numbersPerRow, [indent, indent]);
    % Maximum correlation criterion
    fprintf('\n\n%sBad by max correlation criteria (original):\n', indent)
    printList(reference.noisyOutOriginal.badChannelsFromCorrelation, ...
        numbersPerRow, [indent, indent]);
    fprintf('\n%sBad by max correlation criteria (rereferenced):\n', indent)
    printList(reference.noisyOut.badChannelsFromCorrelation, ...
        numbersPerRow, [indent, indent]);
    % Large deviation criterion
    fprintf('\n\n%sBad by large deviation criteria (original):\n', indent);
    printList(reference.noisyOutOriginal.badChannelsFromDeviation, ...
        numbersPerRow, [indent, indent]);
    fprintf('\n\n%sBad by large deviation criteria (rereferenced):\n', indent);
    printList(reference.noisyOut.badChannelsFromDeviation, ...
        numbersPerRow, [indent, indent]);
    % HF SNR ratio criterion
    fprintf('\n\n%sBad by high frequency noise (low SNR) criteria (original):\n', indent);
    printList(reference.noisyOutOriginal.badChannelsFromHFNoise, ...
        numbersPerRow, [indent, indent]);
    fprintf('\n%sBad by high frequency noise (low SNR) criteria (referenced):\n', indent);
    printList(reference.noisyOut.badChannelsFromHFNoise, ...
        numbersPerRow, [indent, indent]);
    fprintf('\n\n%sBad by Ransac criteria (original):\n', indent);
    printList(reference.noisyOutOriginal.badChannelsFromRansac, ...
        numbersPerRow, [indent, indent]);
        fprintf('\n%sBad by Ransac criteria (rereferenced):\n', indent);
    printList(reference.noisyOut.badChannelsFromRansac, ...
        numbersPerRow, [indent, indent]);
end