function summary = reportReferenced(fid, noisyParameters, numbersPerRow, indent)
%% Extracts and outputs parameters for referencing calculation
% Outputs a summary to file fid and returns a cell array of important messages
    summary = {};
    if ~isempty(noisyParameters.errors.reference)
        summary{end+1} =  noisyParameters.errors.reference;
        fprintf(fid, '%s\n', summary{end});
    end
    if ~isfield(noisyParameters, 'reference')
        summary{end+1} = 'Signal wasn''t referenced';
        fprintf(fid, '%s\n', summary{end});
        return;
    end
    reference = noisyParameters.reference;
    fprintf(fid, 'Rereferencing version %s\n',  ...
        noisyParameters.version.Reference);
    fprintf(fid, 'Sampling rate: %g Hz\n', reference.noisyOut.srate);

    fprintf(fid, 'Noisy channel detection parameters:\n');
    fprintf(fid, '%sRobust deviation threshold (z score): %g\n', ...
        indent, reference.noisyOut.robustDeviationThreshold);
    fprintf(fid, '%sHigh frequency noise threshold (ratio): %g\n', ...
        indent, reference.noisyOut.highFrequencyNoiseThreshold);
    fprintf(fid, '%sCorrelation window size (in seconds): %g\n', ...
        indent, reference.noisyOut.correlationWindowSeconds);
    fprintf(fid, '%sCorrelation threshold (with any channel): %g\n', ...
        indent, reference.noisyOut.correlationThreshold);
    fprintf(fid, '%sBad correlation threshold: %g\n', ...
        indent, reference.noisyOut.badTimeThreshold);
    fprintf(fid, '%s%s(fraction of time with low correlation or dropout)\n', ...
        indent, indent);
    fprintf(fid, '%sRansac sample size : %g\n', ...
        indent, reference.noisyOut.ransacSampleSize);
    fprintf(fid, '%s%s(number channels to use for interpolated estimate)\n', ...
        indent, indent);
    fprintf(fid, '%sRansac channel fraction (for ransac sample size): %g\n', ...
        indent, reference.noisyOut.ransacChannelFraction);
    fprintf(fid, '%sRansacCorrelationThreshold: %g\n', ...
        indent, reference.noisyOut.ransacCorrelationThreshold);
    fprintf(fid, '%sRansacUnbrokenTime (input parameter): %g\n', ...
        indent, reference.noisyOut.ransacUnbrokenTime);
    fprintf(fid, '%sRansacWindowSeconds (in seconds): %g\n', ...
        indent, reference.noisyOut.ransacWindowSeconds);
    fprintf(fid, '%sRansacPerformed: %g\n', indent, ...
        reference.noisyOut.ransacPerformed);
    fprintf(fid, '%sInterpolateHFChannels: %g\n', indent, ...
        reference.interpolateHFChannels);
    fprintf(fid, '\nReference channels (%d channels):\n', ...
        length(reference.referenceChannels));
    printList(fid, reference.referenceChannels, ...
        numbersPerRow, indent);
    fprintf(fid, '\nRereferencedChannels (%d channels):\n', ...
        length(reference.rereferencedChannels));
    printList(fid, reference.rereferencedChannels,  ...
        numbersPerRow, indent);
    
    %% Listing of noisy channels
    outOriginal = reference.noisyOutOriginal;
    outFinal = reference.noisyOut;
    channelLabels = {reference.channelLocations.labels};
    fprintf(fid, '\n\nNoisy channels before referencing:\n');
    printLabeledList(fid, outOriginal.noisyChannels,  ...
        channelLabels(outOriginal.noisyChannels), numbersPerRow, indent);
    fprintf(fid, '\nNoisy channels interpolated after robust referencing:\n');
    printLabeledList(fid, reference.interpolatedChannels, ...
        channelLabels(reference.interpolatedChannels), ...
        numbersPerRow, indent);
    summary{end+1} = ['Interpolated channels: ' ...
        getListString(reference.interpolatedChannels)];
    
    fprintf(fid, '\nRemaining noisy channels after robust referencing:\n');
    printLabeledList(fid, outFinal.noisyChannels, ...
        channelLabels(outFinal.noisyChannels), ...
        numbersPerRow, indent);
    summary{end+1} = ['Potential noisy channels remaining: ' ...
        getListString(outFinal.noisyChannels)];
    
    if ~isempty(reference.badChannelsNotInterpolated)
        fprintf(fid, '\nRemaining bad channels that haven''t been interpolated:\n');
        printLabeledList(fid, reference.badChannelsNotInterpolated, ...
           channelLabels(reference.badChannelsNotInterpolated), ...
           numbersPerRow, indent);
        summary{end+1} = ['Remaining bad channels that haven''t been interpolated:', ...
            getListString(reference.badChannelsNotInterpolated)];
    end
    
    %% NaN criteria
    if isfield(outOriginal, 'badChannelsFromNaNs')   % temporary
    fprintf(fid, '\n\nBad because of NaN (original):\n');
    printLabeledList(fid, outOriginal.badChannelsFromNaNs, ...
        channelLabels(outOriginal.badChannelsFromNaNs), ...
        numbersPerRow, indent);
    fprintf(fid, '\nBad because of NaN (referenced):\n');
    printLabeledList(fid, outFinal.badChannelsFromNaNs, ...
        channelLabels(outFinal.badChannelsFromNaNs), ...
        numbersPerRow, indent);
    end    
     %% All constant criteria
     if isfield(outOriginal, 'badChannelsFromNaNs')   % temporary
    fprintf(fid, '\n\nBad because data is constant (original):\n');
    printLabeledList(fid, outOriginal.badChannelsFromNoData, ...
        channelLabels(outOriginal.badChannelsFromNoData), ...
        numbersPerRow, indent);
    fprintf(fid, '\nBad because data is constant (referenced):\n');
    printLabeledList(fid, outFinal.badChannelsFromNoData, ...
        channelLabels(outFinal.badChannelsFromNoData), ...
        numbersPerRow, indent);   
     end
     %% Dropout criteria
    if isfield(outOriginal, 'badChannelsFromDropOuts')   % temporary
    fprintf(fid, '\n\nBad because of drop outs (original):\n');
    printLabeledList(fid, outOriginal.badChannelsFromDropOuts, ...
        channelLabels(outOriginal.badChannelsFromDropOuts), ...
        numbersPerRow, indent);
    fprintf(fid, '\nBad because of drop outs (referenced):\n');
    printLabeledList(fid, outFinal.badChannelsFromDropOuts, ...
        channelLabels(outFinal.badChannelsFromDropOuts), ...
        numbersPerRow, indent);
    end    
    %% Maximum correlation criterion
    fprintf(fid, '\n\nBad by max correlation criteria (original):\n');
    printLabeledList(fid, outOriginal.badChannelsFromCorrelation, ...
        channelLabels(outOriginal.badChannelsFromCorrelation), ...
        numbersPerRow, indent);
    fprintf(fid, '\nBad by max correlation criteria (referenced):\n');
    printLabeledList(fid, outFinal.badChannelsFromCorrelation, ...
        channelLabels(outFinal.badChannelsFromCorrelation), ...
        numbersPerRow, indent);
    
    %% Large deviation criterion
    fprintf(fid, '\n\nBad by large deviation criteria (original):\n');
    printLabeledList(fid, outOriginal.badChannelsFromDeviation, ...
        channelLabels(outOriginal.badChannelsFromDeviation), ...
        numbersPerRow, indent);
    fprintf(fid, '\n\nBad by large deviation criteria (rereferenced):\n');
    printLabeledList(fid, outFinal.badChannelsFromDeviation, ...
        channelLabels(outFinal.badChannelsFromDeviation), ...
        numbersPerRow, indent);
      
    %% HF SNR ratio criterion
    fprintf(fid, '\n\nBad by high frequency noise (low SNR) criteria (original):\n');
    printLabeledList(fid, outOriginal.badChannelsFromHFNoise, ...
        channelLabels(outOriginal.badChannelsFromHFNoise), ...
        numbersPerRow, indent);
    fprintf(fid, '\nBad by high frequency noise (low SNR) criteria (referenced):\n');
    printLabeledList(fid, outFinal.badChannelsFromHFNoise, ...
        channelLabels(outFinal.badChannelsFromHFNoise), ...
        numbersPerRow, indent);
      
    %% Ransac criteria
    fprintf(fid, '\n\nBad by Ransac criteria (original):\n');
    printLabeledList(fid, outOriginal.badChannelsFromRansac, ...
        channelLabels(outOriginal.badChannelsFromRansac), ...
        numbersPerRow, indent);
    fprintf(fid, '\nBad by Ransac criteria (rereferenced):\n');
    printLabeledList(fid, outFinal.badChannelsFromRansac, ...
        channelLabels(outFinal.badChannelsFromRansac), ...
        numbersPerRow, indent);
 
end