function showBadWindows(beforeValues, afterValues, beforeTimeScale, ...
        afterTimeScale, numberChannels, legendStrings, name, thresholdName)
% Display number of bad channels before and after referencing by window
verticalLabel = ['Number of channels (out of '  num2str(numberChannels) ')'];
averageBefore = mean(beforeValues);
averageAfter = mean(afterValues);
fprintf(['\n\nOn average a fraction %g (%g channels)\n' ...
         'exceeds the %s \n' ...
         'in each time window %s\n'], ...
         averageBefore/numberChannels, averageBefore, ...
         thresholdName, lower(legendStrings{1}));
fprintf(['On average a fraction %g (%g channels)\n' ...
         'exceeds the %s \n' ...
         'in each time window %s\n'], ...
         averageAfter/numberChannels, averageAfter, ...
         thresholdName, lower(legendStrings{2}));
tString = { name, ['Channels exceeding ' thresholdName]}; 
figure('Name', tString{2})
hold on
plot(beforeTimeScale, beforeValues, '+k')
plot(afterTimeScale, afterValues, 'or')
hold off
xlabel('Seconds')
ylabel(verticalLabel);
legend(legendStrings{1}, legendStrings{2}, ...
      'Location', 'SouthOutside', 'Orientation', 'Horizontal' )
title(tString, 'Interpreter', 'None');

