function [fractionBefore, fractionAfter] = ...
        showBadWindows(beforeValues, afterValues, beforeTimeScale, ...
        afterTimeScale, numberChannels, legendStrings, name, thresholdName)
% Display number of bad channels before and after referencing by window
verticalLabel = ['Number of channels (out of '  num2str(numberChannels) ')'];
averageBefore = mean(beforeValues);
averageAfter = mean(afterValues);
fractionBefore = mean(beforeValues)/numberChannels;
fractionAfter = mean(afterValues/numberChannels);
fprintf(['\n\nOn average a fraction %g (%g channels)\n' ...
         'does not meet the %s threshold\n' ...
         'in each time window %s\n'], ...
         fractionBefore, averageBefore, ...
         thresholdName, lower(legendStrings{1}));
fprintf(['On average a fraction %g (%g channels)\n' ...
         'does not meet the %s threshold\n' ...
         'in each time window %s\n'], ...
         fractionAfter, averageAfter, ...
         thresholdName, lower(legendStrings{2}));
tString = { name, ['Channels not meeting ' thresholdName ' threshold']}; 
figure('Name', tString{2})
hold on
plot(beforeTimeScale, beforeValues, '+k')
plot(afterTimeScale, afterValues, 'or')
hold off
xlabel('Seconds')
ylabel(verticalLabel);
legend(legendStrings{1}, legendStrings{2}, ...
      'Location', 'SouthOutside', 'Orientation', 'Horizontal' )
title(tString, 'Interpreter', 'None');

