function referenceStruct = getReferenceStructure()
% Creates an empty reference structure
referenceStruct = struct( ...
    'referenceChannels', [], ...
    'specificReferenceChannels', [], ...
    'rereferencedChannels', [], ...
    'channelLocations', [], ...
    'channelInformation', [], ...
    'maxInterpolationIterations', [], ...
    'actualInterpolationIterations', [], ...
    'interpolatedChannelsFromNaNs', [], ...
    'interpolatedChannelsFromNoData', [], ...
    'interpolatedChannelsFromHFNoise', [], ...
    'interpolatedChannelsFromCorrelation', [], ...
    'interpolatedChannelsFromDeviation', [], ...
    'interpolatedChannelsFromRansac', [], ...
    'interpolatedChannelsFromDropOuts', [], ...
    'interpolatedChannels', [], ...
    'channelsStillBad', [], ...
    'referenceType', [],  ...
    'referenceSignalWithNoisyChannels', [], ...
    'referenceSignal', [], ...
    'noisyOutOriginal', [], ...
    'noisyOut', [] ...
    );