function std2ver = getStandardLevel2Version()

std2ver = struct('HighPass', 'v0.22', 'LineNoise', 'v0.22', ...
                 'Resampling', 'v0.22', ...
                 'Reference', 'v0.22', 'Interpolation', 'v0.22');