function std2ver = getStandardLevel2Version()

std2ver = struct('HighPass', 'v0.19', 'LineNoise', 'v0.19', ...
                 'Resampling', 'v0.19', ...
                 'Reference', 'v0.19', 'Interpolation', 'v0.19');