function std2ver = getStandardLevel2Version()

std2ver = struct('HighPass', 'v0.24', 'LineNoise', 'v0.24', ...
                 'Resampling', 'v0.24', ...
                 'Reference', 'v0.24', 'Interpolation', 'v0.24');