function badChannels = getBadChannelStructure()
  badChannels = struct( ...
    'all', [], ...
    'badChannelsFromNaNs', [], ...
    'badChannelsFromNoData', [], ...
    'badChannelsFromHFNoise', [], ...
    'badChannelsFromCorrelation', [], ...
    'badChannelsFromDeviation', [], ...
    'badChannelsFromRansac', [], ...
    'badChannelsFromDropOuts', []);