function prepver = getPrepPipelineVersion()

prepver = struct('Detrend', 'v0.51', 'GlobalTrend', 'v0.51', ...
                 'LineNoise', 'v0.51', 'Resampling', 'v0.51', ...
                 'Reference', 'v0.51', 'Interpolation', 'v0.51');