function prepver = getPrepPipelineVersion()

prepver = struct('Detrend', 'v0.52', 'GlobalTrend', 'v0.52', ...
                 'LineNoise', 'v0.52', 'Resampling', 'v0.52', ...
                 'Reference', 'v0.52', 'Interpolation', 'v0.52');