function prepver = getPrepPipelineVersion()

prepver = struct('Detrend', 'v0.43', 'GlobalTrend', 'v0.43', ...
                 'LineNoise', 'v0.43', 'Resampling', 'v0.43', ...
                 'Reference', 'v0.43', 'Interpolation', 'v0.43');