function referenceStruct = getReferenceStructure()
% Creates an empty reference structure
referenceStruct = struct( ...
    'referenceChannels', [], ...
    'evaluationChannels', [], ...
    'rereferencedChannels', [], ...
    'channelLocations', [], ...
    'channelInformation', [], ...
    'maxReferenceIterations', [], ...
    'actualReferenceIterations', [], ...
    'interpolatedChannels', getBadChannelStructure(), ...
    'referenceSignal', [], ...
    'referenceSignalOriginal', [], ...
    'noisyStatistics', [], ...
    'reportingLevel', [] ...
    );