function std2ver = getStandardLevel2Version()

std2ver = struct('Detrend', 'v0.40', 'GlobalTrend', 'v0.40', ...
                 'LineNoise', 'v0.40', 'Resampling', 'v0.40', ...
                 'Reference', 'v0.40', 'Interpolation', 'v0.40');